In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:


np_height =np.array([4.5,5.2, 5.6,6.3,7.1,5.8])
print(type(np_height))



<class 'numpy.ndarray'>


In [4]:


np_weight= np.array([100,98,67,71,88,77] )
np_weight



array([100,  98,  67,  71,  88,  77])

In [5]:
bmi = np_weight / np_height **2
bmi


array([4.9382716 , 3.62426036, 2.13647959, 1.78886369, 1.74568538,
       2.28894174])

In [6]:


arr1 = np.array([1,2,3,4,5])
arr1.ndim



1

In [7]:


extra = [1,2.2,"hello",False]
print(type(extra))



<class 'list'>


In [8]:
np.array([1,2.2,"hello",False]) # Supports only one type of data

array(['1', '2.2', 'hello', 'False'], dtype='<U32')

In [9]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
list1 + list2 # merge elements like append


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [10]:


np_list1 = np.array([1,2,3,4,5])
np_list2 = np.array([6,7,8,9,10])
np_list1 + np_list2 # Sum the elements



array([ 7,  9, 11, 13, 15])

In [11]:


np_list1[2]



np.int64(3)

In [12]:
np_list2 > 6

array([False,  True,  True,  True,  True])

In [13]:
np_list2[np_list2 > 6]

array([ 7,  8,  9, 10])

In [14]:
np_list2[np_list2 > 9]

array([10])

In [15]:
# [ 1,2
#   3,4]

arr_2d = np.array([[1,2],[3,4],[5,6]])
arr_2d
# shape (rows,columns) (3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
arr_2d.ndim

2

In [17]:
# to get 3 element
arr_2d[1,0]

np.int64(3)

In [18]:


arr_2d[1]



array([3, 4])

In [19]:


# to get last two matrix
arr_2d[1:] # include, exclude



array([[3, 4],
       [5, 6]])

In [20]:
arr_2d[:2]

array([[1, 2],
       [3, 4]])

In [21]:


# to get 5 
arr_2d[2,0]



np.int64(5)

In [ ]:


# [ 1, 2, 3
#   4, 5, 6
#   7, 8, 9]

# 2D -> 3X3



In [22]:


arr_3d = np.array([[
        [3, 4],
       [5, 6]],
       
       [[11, 12],
       [20, 22]]]
       )
arr_3d



array([[[ 3,  4],
        [ 5,  6]],

       [[11, 12],
        [20, 22]]])

In [23]:


arr_3d[1,0,0]



np.int64(11)

In [24]:
arr_3d[1,1,1]

np.int64(22)

In [25]:


arr_3d = np.array([[
        [3, 4,33],
       [5, 6,88],
       [0, 14,22]],
       
       [[11, 12,55],
       [20, 22,44],
       [125, 120,199]]]
       )
arr_3d



array([[[  3,   4,  33],
        [  5,   6,  88],
        [  0,  14,  22]],

       [[ 11,  12,  55],
        [ 20,  22,  44],
        [125, 120, 199]]])

In [27]:
arr_3d.shape


(2, 3, 3)

In [28]:
arr_3d[1,2,1]

np.int64(120)

In [29]:
arr_3d[0,1,1]

np.int64(6)

In [30]:


np_list1 = np.array([1,2,3,4,5])
np_list2 = np.array([6,7,8,9,10])

np_list1.shape
np_list1.size
np_list1.dtype
# Serach more properties 



dtype('int64')

In [31]:


np.zeros((2,3))



array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:


np_list1 = np.array([1,2,3,4,5])
np_list2 = np.array([6,7,8,9,10])

np_list1 + np_list2



array([ 7,  9, 11, 13, 15])